students:
    resource: ./routes/students.yml
    prefix: /api
    name_prefix: students_
    requirements:
        _format: json

marks:
    resource: ./routes/marks.yml
    prefix: /api
    name_prefix: marks_
    requirements:
        _format: json